services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        value: postgresql://strapi_db_ziyx_user:F6WMLh10nltnXDNfmbXHydcwuzMEQ8fo@dpg-d8rvmfsvikkc7392ju8g-a/strapi_db_ziyx
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: APP_KEYS
        value: EIJHiUMD79fnX0TpzYdjka4s63hBmytK,0wZNu3A5SoY1bmqIUpk6xaRPVev74Lk8
      - key: API_TOKEN_SALT
        value: 0wZNu3A5SoY1bmqIUpk6xaRPVev74Lk8
      - key: ADMIN_JWT_SECRET
        value: VpbAWs3qH7rt52h6oZRuW0J1G1eJBCFY
      - key: JWT_SECRET
        value: 6uViSjQ2t17EIh4mN1YPF3q5neCdvJZk
      - key: NODE_ENV
        value: production
    disk:
      name: strapi-uploads
      mountPath: /app/public/uploads
      sizeGB: 5

databases:
  - name: strapi-db
    plan: starter